<a href="https://colab.research.google.com/github/BelenUrdangarin/Entregables---Urdangarin/blob/main/Notebook_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Ya dijimos previamente que un proyecto de data science tiene varias etapas:

1. Recolecci√≥n de Datos
2. Exploraci√≥n y Procesamiento de los datos
3. Modelado
4. Puesta en Producci√≥n

En la clase anterior, hicimos el analisis exploratorio de los datos y pudimos observar el tipo de datos que teniamos. Pudimos hacernos preguntas y ver algunos patrones. Todo ese conocimiento que adquirimos es √∫til para llevar a cabo la pr√≥xima parte de esta etapa: el procesamiento de los datos.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

<font size=5>  üöÄ Procesamiento de datos üë©üèΩ‚Äçüíª</font>

Una vez que visualizamos y exploramos el dataset tenemos una idea de como lucen nuestros datos. Es por eso que ahora debemos empezar a preparar nuestros datos para los siguientes pasos seg√∫n lo que aprendimos de ellos y las preguntas que nos planteamos.

In [4]:
blackfriday = pd.read_csv('https://raw.githubusercontent.com/BelenUrdangarin/Entregables---Urdangarin/refs/heads/main/black_friday_reducido.csv', sep=';')
blackfriday.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0
5,1000005,P00251242,M,26.0,20.0,A,1,1,5,11.0,NaN,5254.0
6,1000006,P00190242,F,53.0,9.0,A,1,0,4,5.0,NaN,2079.0
7,1000008,P00249542,M,27.0,12.0,C,4,1,1,5.0,15.0,19614.0
8,1000008,P00214442,M,33.0,12.0,C,4,1,8,NaN,NaN,5982.0
9,1000009,P00135742,M,30.0,17.0,C,0,0,6,8.0,NaN,16662.0

In [5]:
blackfriday.shape

(188323, 12)

In [6]:
blackfriday.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

#### 1) TRANSFORMACION DE VARIABLES

- La mayor√≠a de los algoritmos de machine learning no admiten `strings` como variables y requieren que las variables sean numericas. Por ese motivo, es necesario convertir las variables categoricas en su representaci√≥n numerica. Para esto hay varias opciones que iremos viendo.

**`LabelEncoder()`**

In [7]:
from sklearn.preprocessing import LabelEncoder # Con Label encoder lo que hacemos es cambiar una categoria que tenia nombre por ejemplo de ciudades en que las ponga 0,1,2,3, ect

In [8]:
test_encoder = LabelEncoder() #Ejecutamos la funci√≥n, el label enconder agarra un valor y le pone un numero, independientemente de la cantidad de valores diferentes

In [10]:
blackfriday.loc[:, 'City_Category'] = test_encoder.fit_transform(blackfriday['City_Category'])
# Para todas las filas de city category, con el test encoder le da un valor por cada categoria de esa columna

In [15]:
blackfriday.head(10) #Comprobamos el cambio

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00248942,F,15.0,NaN,0,2,0,1,6.0,14.0,15200.0
1,1000001,P00087842,NaN,15.0,10.0,0,2,0,12,NaN,NaN,1422.0
2,1000001,P00085442,F,15.0,10.0,0,2,0,12,14.0,NaN,1057.0
3,1000003,P00193542,M,28.0,15.0,0,3,0,1,2.0,NaN,15227.0
4,1000004,P0097242,M,48.0,NaN,1,2,1,1,16.0,NaN,15686.0
5,1000005,P00251242,M,26.0,20.0,0,1,1,5,11.0,NaN,5254.0
6,1000006,P00190242,F,53.0,9.0,0,1,0,4,5.0,NaN,2079.0
7,1000008,P00249542,M,27.0,12.0,2,4,1,1,5.0,15.0,19614.0
8,1000008,P00214442,M,33.0,12.0,2,4,1,8,NaN,NaN,5982.0
9,1000009,P00135742,M,30.0,17.0,2,0,0,6,8.0,NaN,16662.0

**`get_dummies()`**

*get_dummies* convierte una variable categorica en variables ficticias/indicadoras, cada variable se convierte en tantas variables 0/1 como valores diferente tenga.

In [16]:
pd.get_dummies(blackfriday, columns=["Gender"]) #Convierte en valores booleanos donde se encuentre un valor

,User_ID,Product_ID,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M
0,1000001,P00248942,15.0,NaN,0,2,0,1,6.0,14.0,15200.0,True,False
1,1000001,P00087842,15.0,10.0,0,2,0,12,NaN,NaN,1422.0,False,False
2,1000001,P00085442,15.0,10.0,0,2,0,12,14.0,NaN,1057.0,True,False
3,1000003,P00193542,28.0,15.0,0,3,0,1,2.0,NaN,15227.0,False,True
4,1000004,P0097242,48.0,NaN,1,2,1,1,16.0,NaN,15686.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188318,1004736,P00157542,24.0,NaN,0,1,1,8,14.0,NaN,1994.0,False,True
188319,1004736,P00250642,24.0,20.0,0,1,1,11,NaN,NaN,5930.0,False,True
188320,1004736,P00023142,23.0,20.0,0,1,1,5,14.0,NaN,7042.0,False,True
188321,1004737,P00221442,43.0,16.0,2,1,0,1,2.0,5.0,11852.0,False,True
188322,1004737,P00118242,43.0,16.0,2,1,0,5,8.0,NaN,6875.0,False,True

In [17]:
pd.get_dummies(blackfriday["Gender"]) #Donde hay dos falsos es un nan

            F      M
0        True  False
1       False  False
2        True  False
3       False   True
4       False   True
...       ...    ...
188318  False   True
188319  False   True
188320  False   True
188321  False   True
188322  False   True

[188323 rows x 2 columns]

In [18]:
blackfriday[['female', 'male']] = pd.get_dummies(blackfriday["Gender"])
# Lo que hace aca es aplicar el get dummies pero en dos filas nuevas y dejar la columna gender en el documento

In [20]:
blackfriday.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,female,male
0,1000001,P00248942,F,15.0,NaN,0,2,0,1,6.0,14.0,15200.0,True,False
1,1000001,P00087842,NaN,15.0,10.0,0,2,0,12,NaN,NaN,1422.0,False,False
2,1000001,P00085442,F,15.0,10.0,0,2,0,12,14.0,NaN,1057.0,True,False
3,1000003,P00193542,M,28.0,15.0,0,3,0,1,2.0,NaN,15227.0,False,True
4,1000004,P0097242,M,48.0,NaN,1,2,1,1,16.0,NaN,15686.0,False,True

**`OneHotEncoder()`**

El *OneHotEncoder* Transforma los datos categ√≥ricos a un formato que los modelos de aprendizaje autom√°tico pueden comprender y utilizar f√°cilmente . Esta transformaci√≥n permite tratar cada categor√≠a de forma independiente sin implicar relaciones falsas entre ellas.
T√©cnica de preprocesamiento de datos categ√≥ricos que convierte variables categ√≥ricas en una representaci√≥n num√©rica binaria que puede ser utilizada por algoritmos de machine learning.
Convierte cada categor√≠a en una columna distinta con valores 0 o 1, indicando la presencia de esa categor√≠a en cada fila.

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
blackfriday['Gender'].unique() #Vemos cuantos valores unicos hay en la categoria Gender

array(['F', nan, 'M'], dtype=object)

In [38]:
gender_encoder = OneHotEncoder()

In [39]:
gender_encoder.fit_transform(blackfriday[['Gender']]).toarray()
#Genera un array con ceros y unos en los lugares donde se encuentre una categoria

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [40]:
gender_encoder.categories_ #Chequeamos las categorias del gender encoder

[array(['F', 'M', nan], dtype=object)]

In [41]:
niveles = gender_encoder.categories_[0].tolist()
#Te permite ver qu√© categor√≠as fueron codificadas y en qu√© orden est√°n representadas en las columnas codificadas.

In [27]:
one_hot_gender = pd.DataFrame(gender_encoder.fit_transform(blackfriday[['Gender']]).toarray(), columns=niveles)

In [42]:
one_hot_gender

#gender_encoder.fit_transform(...)
#Aplica el OneHotEncoder a la columna 'Gender' del DataFrame blackfriday. Esto convierte cada categor√≠a (por ejemplo, 'Male', 'Female') en una fila de ceros y unos.

#.toarray()
#Convierte la salida (que es una matriz dispersa por defecto) a un array NumPy completo con ceros y unos.

#pd.DataFrame(..., columns=niveles)
#Crea un nuevo DataFrame con ese array, usando las categor√≠as (niveles) como nombres de columnas. As√≠ cada columna representa una categor√≠a con 1 si el registro pertenece a esa categor√≠a, y 0 si no.

          F    M  NaN
0       1.0  0.0  0.0
1       0.0  0.0  1.0
2       1.0  0.0  0.0
3       0.0  1.0  0.0
4       0.0  1.0  0.0
...     ...  ...  ...
188318  0.0  1.0  0.0
188319  0.0  1.0  0.0
188320  0.0  1.0  0.0
188321  0.0  1.0  0.0
188322  0.0  1.0  0.0

[188323 rows x 3 columns]

In [43]:
new_df = pd.concat([blackfriday, one_hot_gender], axis=1)
#concatena la trnasformacion del onehot con el frame viejo

In [45]:
new_df.head() #Tenemos lo hecho con label_encoder con lo de onehot y el get_dummies

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,female,male,F,M,NaN
0,1000001,P00248942,F,15.0,NaN,0,2,0,1,6.0,14.0,15200.0,True,False,1.0,0.0,0.0
1,1000001,P00087842,NaN,15.0,10.0,0,2,0,12,NaN,NaN,1422.0,False,False,0.0,0.0,1.0
2,1000001,P00085442,F,15.0,10.0,0,2,0,12,14.0,NaN,1057.0,True,False,1.0,0.0,0.0
3,1000003,P00193542,M,28.0,15.0,0,3,0,1,2.0,NaN,15227.0,False,True,0.0,1.0,0.0
4,1000004,P0097242,M,48.0,NaN,1,2,1,1,16.0,NaN,15686.0,False,True,0.0,1.0,0.0

**`binning`**

In [46]:
print(blackfriday.Age.min())
print(blackfriday.Age.max())
#Saca el maximo y el minimo de la categoria Age

14.0
74.0

In [47]:
blackfriday["Age"] = pd.to_numeric(blackfriday["Age"], errors='coerce')

#pd.to_numeric(...): convierte cualquier dato en formato texto a num√©rico.
#errors='coerce': si encuentra un valor que no puede convertir a n√∫mero, lo reemplaza por NaN (valor nulo).

In [48]:
bin_age = [10, 17, 70, 80]

labels = ["Adolescente", "Adulto", "Anciano"]

age_categories = pd.cut(blackfriday["Age"], bins=bin_age, labels=labels)

#Crea categorias en la columna age con el comando cut
#Adolescente: edades entre 10 y 17
#Adulto: edades entre 17 y 70
#Anciano: edades entre 70 y 80

In [50]:
age_categories

0         Adolescente
1         Adolescente
2         Adolescente
3              Adulto
4              Adulto
             ...
188318         Adulto
188319         Adulto
188320         Adulto
188321         Adulto
188322         Adulto
Name: Age, Length: 188323, dtype: category
Categories (3, object): ['Adolescente' < 'Adulto' < 'Anciano']